### ISSUE TITLE
Correct version python file?

### ISSUE THREAD

**Issue by echarles** [jupyter/nbclassic#101]
What is the best way to define the version for nbclassic, taking into account the jupyter_releaser process

For now, the check_release job is failing (see. https://github.com/jupyter/nbclassic/runs/6521439283?check_suite_focus=true) with

```
0.0.4
:: Bumping from 0.3.7 to 0.0.5
Error: nbclassic/__version__.py does not exist
Traceback (most recent call last):
```

Should we readd a `__version__.py` file that reexports the `__version__`  defined in `_version.py`. In that case, will the jupyter_releaser still be happy?

Any advice welcome here

cc/ @blink1073 @Zsailer

**Comment by blink1073** [comment]
It should be `nbclassic/_version.py` in `pyproject.toml`.  It is using a regex to read the version from the file.

**Comment by echarles** [comment]
Thx @blink1073 I have opened https://github.com/jupyter/nbclassic/pull/102 to fix the releaser ci job and it is now failing with `error: [Errno 2] No such file or directory: 'pybabel'` on https://github.com/jupyter/nbclassic/runs/6524838596?check_suite_focus=true#step:9:1284
