### ISSUE TITLE
Update to latest Selenium API

### ISSUE THREAD

**Issue by echarles** [jupyter/nbclassic#115]
All selenium tests are failing on main branch, see https://github.com/jupyter/nbclassic/pull/114

cc/ @RRosio @ericsnekbytes

**Comment by jtpio** [comment]
FYI this is likely related to the latest `4.3.0` release of `selenium` and the removal of deprecated methods.

Also noticed in https://github.com/jupyter/nbgrader/issues/1612

**Comment by echarles** [comment]
yep just pined selenium and it is much better.

**Comment by echarles** [comment]
https://github.com/jupyter/nbclassic/pull/114 is ready for review. It pins selenium. We can leave this issue open to plan an removal of the selenium deprecated APIs.

**Comment by jtpio** [comment]
Their docstrings say:

```
Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead",
```

So maybe worth trying to update to the new methods?

**Comment by echarles** [comment]
The Selenium tests are being ported to Playwright in https://github.com/jupyter/nbclassic/pull/139

Closing.
