### ISSUE TITLE
Error with nbclassic==0.4.0, JupyterLab<4 and notebook<7

### ISSUE THREAD

**Issue by brichet** [jupyter/nbclassic#121]
This check : https://github.com/jupyter/nbclassic/blob/3ebe3d72182379791ba61c397a4b131df810abe5/nbclassic/__init__.py#L45-L46 seems to work only if `Notebook` is not installed or in a version `>= 7`.

Running :
```
pip install "jupyterlab<4"
pip install "notebook<7"
jupyter server extension list
```
raises :
```
File "/home/brichet/miniconda3/envs/nbclassic-test/lib/python3.10/site-packages/nbclassic/__init__.py", line 46, in <module>
    assert NotebookIPythonHandler.__name__ == "JupyterHandler"
AssertionError
```
which is logic because the following command works : https://github.com/jupyter/nbclassic/blob/3ebe3d72182379791ba61c397a4b131df810abe5/nbclassic/__init__.py#L12-L13

Maybe a test on the `notebook` version is missing ?

If this is the desired behavior this issue should be opened in `JupyterLab 3.4.x` to pin the `nbclassic` version `<0.4.0`.

**Comment by echarles** [comment]
Thx for reporting. We have been discussing that in https://github.com/jupyter/nbclassic/issues/120#issuecomment-1173850619

I have opened a fix on https://github.com/jupyter/nbclassic/pull/122
