### ISSUE TITLE
Adding a webhook to build docs automatically with new commits

### ISSUE THREAD

**Issue by RRosio** [jupyter/nbclassic#151]
With the [nbclassic readthedocs documentation](https://nbclassic.readthedocs.io/en/latest/) up, a nice feature to make use of is to add a webhook to allow the documentation to build automatically. We can also add a badge to show the status of the docs in the Readme file for visibility.

**Comment by echarles** [comment]
@RRosio I think you said that the hook was enabled, but don't have the details. Is the website built on each merged PR? 

For the badges, https://github.com/jupyter/notebook has a bunch of those, including the docs. 

<img width="513" alt="Screenshot 2022-10-10 at 09 41 27" src="https://user-images.githubusercontent.com/226720/194818856-8c406d4a-644c-4ca5-b7cf-856351f19b9e.png">

The code for that is 

```

![Github Actions Status](https://github.com/jupyter/notebook/workflows/Build/badge.svg)
[![Documentation Status](https://readthedocs.org/projects/jupyter-notebook/badge/?version=latest)](https://jupyter-notebook.readthedocs.io/en/latest/?badge=latest)
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/jupyter/notebook/main?urlpath=tree)
[![codecov](https://codecov.io/gh/jupyter/notebook/branch/master/graph/badge.svg)](https://codecov.io/gh/jupyter/notebook)

```

**Comment by RRosio** [comment]
@echarles Yes I believe that with each PR merged to the main branch the docs are built.
Thank you for the code samples I will work on adding them in a new PR!

**Comment by RRosio** [comment]
Badge was added by #160 so I will close this issue as it's complete at this time.
