### ISSUE TITLE
/nbclassic/ should redirect to /nbclassic/tree

### ISSUE THREAD

**Issue by mcrutch** [jupyter/nbclassic#163]
If nbclassic is installed along-side NB7 and someone goes to /nbclassic/ it should redirect to /nbclassic/tree/.  This is similar to how going to / would redirect to /tree or /lab depending on your settings.  Instead you get a 404 page which makes it seem like nbclassic is not installed.

**Comment by echarles** [comment]
Makes sense. We will open a PR for that. Thx for reporting.

**Comment by echarles** [comment]
@mcrutch I have opened https://github.com/jupyter/nbclassic/pull/166 to fix this. If you have cycles, could you double check and report if it works for you. Thx again.
