### ISSUE TITLE
nbclassic does not work with Notebook v7 if Jupyter server is not running at /

### ISSUE THREAD

**Issue by mcrutch** [jupyter/nbclassic#164]
When we run Jupyter we run it at /Jupyter/ or similar because it is one of many services running on the same box.  I can visit nbclassic as /Jupyter/nbclassic/tree but then it munges the url to be /nbclassic/Jupyter/noteoboks/<notebookname>.ipynb

I confirmed IPython.notebook.base_url has the correct value (/Jupyter/) when in the notebooks page, so it looks like the nbclassic, and base_url components are just being switched somewhere

**Comment by mcrutch** [comment]
Pretty sure it is because you have the parameters flipped in situations like this.  The Base URL of the server should be inserted BEFORE the url of NBClassic.

https://github.com/jupyter/nbclassic/blob/7752bd880122755c13273e0dad53fb66b8797f9b/nbclassic/static/tree/js/newnotebook.js#L88

**Comment by echarles** [comment]
Great catch. do you feel like opening a PR for this?

**Comment by mcrutch** [comment]
I am digging through this a bit now, but it is hard to trace all the spots affected
