### ISSUE TITLE
Use a standard version file

### ISSUE THREAD

**Issue by blink1073** [jupyter/nbclassic#17]
Copy https://github.com/jupyterlab/jupyterlab-module-federation/tree/a182378035da68fe37fe59e9d5798d07e1534bc6/md_package

**Comment by echarles** [comment]
Is this still applicable? Is this linked to https://github.com/jupyter/nbclassic/issues/135?

**Comment by blink1073** [comment]
I'm not sure what I meant here.  😅

**Comment by echarles** [comment]
Maybe one of those days :)
