### ISSUE TITLE
static and templates folder are not present in the release

### ISSUE THREAD

**Issue by echarles** [jupyter/nbclassic#204]
Probably a consequence of https://github.com/jupyter/nbclassic/pull/181, the `static` and `templates` folders are no more present in the release (https://pypi.org/project/nbclassic/0.5.0 had to be yanked).

`static` and `templates` folder are however present further a `pip install .` (also present in editable mode with ``pip install -e .`).

cc/ @blink1073

**Comment by blink1073** [comment]
Because they are in `.gitignore` they must be manually included, as we do in [`jupyter_server`](https://github.com/jupyter-server/jupyter_server/blob/91c59423837caf6e3923ccf3028f5bb176db5c26/pyproject.toml#L142).

**Comment by echarles** [comment]
@blink1073 I have tested locally with the merged https://github.com/jupyter/nbclassic/issues/204, running `python -m build` and the generated wheel does not contain the `static` nor `templates`. I am expecting that the release will also not contain them. Any idea?

**Comment by echarles** [comment]
`components` was present in .gitignore, but not `templates`. I guess the change of https://github.com/jupyter/nbclassic/issues/204 has not modified the behavior.

I have tried to tune `MANIFEST.in` without luck. I am going to continue to search. If I can not find a solution in the short term and as users are waiting for a release (with CVE fixes) I guess I will open a PR to temporary revert https://github.com/jupyter/nbclassic/pull/181

**Comment by echarles** [comment]
Ok, I have a fix with https://github.com/jupyter/nbclassic/pull/206 (at least python -m build creates a correct wheel on my env with the templates and static folders).

@blink1073
