### ISSUE TITLE
Missing icons in the news banner on 0.5.2

### ISSUE THREAD

**Issue by jtpio** [jupyter/nbclassic#223]
Trying Notebook 7, JupyterLab 4 and NBClassic installed together on Binder with https://gist.github.com/jtpio/35a72862c8be13dee31b61ebac2d9786

It appears the icons in the banner added in https://github.com/jupyter/nbclassic/pull/215 are not rendered properly (using Firefox 110 on Fedora 37):

![image](https://user-images.githubusercontent.com/591645/220917290-84e88a0f-969a-42a5-ac0d-15c9b05f8587.png)

**Comment by echarles** [comment]
Thx for reporting. This has been fixed in https://github.com/jupyter/nbclassic/pull/220

We need to cut a release with that.

**Comment by jtpio** [comment]
ok thanks for the confirmation.

Closing as fixed!
