### ISSUE TITLE
nbclassic >=0.5 breaks jupyter_nbextensions_configurator

### ISSUE THREAD

**Issue by scmmmh** [jupyter/nbclassic#227]
Hi,

It seems that the nbclassic >= 0.5 releases break the jupyter_nbextensions_configurator extension, because it cannot find the corrected "marked.js" file. It is trying to load "/static/nbclassic/components/marked/lib/marked.js?v=20230228105802", but cannot find that. If I pin nbclassic < 0.5, then it works.

Best,
Mark

**Comment by echarles** [comment]
Thx for reporting.

This is due to https://github.com/jupyter/nbclassic/pull/201 and should be fixed in the https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator repository.

cc/ @RRosio @ericsnekbytes

**Comment by scmmmh** [comment]
I've re-reported it there.

**Comment by jslorrma** [comment]
Opened a fixing pull request in https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/152
