### ISSUE TITLE
Add an option to disable the news / Notebook 7 migration banner

### ISSUE THREAD

**Issue by andrii-i** [jupyter/nbclassic#242]
#215 introduced news / Notebook 7 migration banner. This a good informational feature for self-managed users but it presents problems in settings where user's environment is managed and updating something can lead to environment breaking or not working properly.

In Notebook 7 you can disable the banner display using show_banner trait ([#6808](https://github.com/jupyter/notebook/pull/6808)). Making the same option available in nbclassic would solve the problem.

**Comment by matthew-brett** [comment]
Agree - this is frustrating and confusing for our users of a JupyterHub cluster.

**Comment by echarles** [comment]
I can work on this begin next week.

**Comment by echarles** [comment]
See https://github.com/jupyter/notebook_shim/pull/29 and https://github.com/jupyter/nbclassic/pull/243

This feature can take some time as depends on a new `notebook_shim` release.

**Comment by santiagobasulto** [comment]
@RRosio thanks! which version of `nbclassic` is this/will this fix tied to?

**Comment by echarles** [comment]
@santiagobasulto this will be available in the next release. I will try to cut one this week.

**Comment by echarles** [comment]
@santiagobasulto nbclassic `0.5.6` is released and allows you to disable the banner display with `--NotebookApp.show_banner=False`.

**Comment by santiagobasulto** [comment]
Thanks @echarles!!!

**Comment by matthew-brett** [comment]
My attempt to apply this config to a JupyterHub setup : https://github.com/lisds/lisds-images/commit/4ced0704a103356e40fb72d342a28b24751eb0a8
